### PR TITLE
Add /status route

### PR DESCRIPTION
**Pull request by sbillig**
Untested, may or may not work.

### CODE REVIEW

**Comment by DanSchoppe** [comment]
👋 Thanks @sbillig for the PR! This looks similar to my `status` branch 😂

I had naively been trying to use the `describeInstances` method. I had put this down when I ran into an authorization snag, despite the additional IAM grant below:
```
        "ec2:DescribeInstanceStatus",
        "ec2:DescribeInstances",
```

Anyway, I like that you found the `describeInstanceStatus` method. I'll see what a Terraform apply looks like and give it a try!

**Comment by sbillig** [comment]
Oops, didn't notice that branch. Also didn't notice the IAM permission. Added.

**Comment by DanSchoppe** [comment]
Well, I figured out the authorization problem. Found this little nugget in the AWS SDK documentation 🙄.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policies-ec2-console.html

> The Amazon EC2 ec2:Describe* API actions do not support resource-level permissions, so you cannot control which individual resources users can view in the console. Therefore, the * wildcard is necessary in the Resource element of the above statement.

So I added `ec2:DescribeInstanceStatus` with a wildcard resource.

I also took the opportunity to clean up the returned text from the Lambda. The "control" routes now simply print `[beforeState] -> [currentState]` and the status route simply prints `[currentState]`.

There's still a problem with how I'm using the callback in an error case (like when you run `/start` and the instance in in a `/stopping` status, it throws). All that comes back from API Gateway is an internal server error. I'll fix this another night 😄

**Comment by DanSchoppe** [comment]
If this all looks good to you @sbillig, I'll go ahead and merge. Thanks for the contribution! 🙏

**Pull request merged**
